config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #get 'pages/home'
  #root 'store#index', as: 'store_index'

  root to: 'admin/dashboard#index'
  get 'store/index'

  resources :service_appointments
  resources :clients
  resources :products
  resources :purchase_orders
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin_user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if admin_user.superadmin?
    #     can :manage, :admin_user
    #   else
    #     can :read, :admin_user
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :service_appointments
end

app/models/product.rb
class Product < ApplicationRecord

  before_destroy :ensure_not_referenced_by_any_line_item
  #accepts_nested_attributes_for :image, :allow_destroy => true
  mount_uploader :image, ImageUploader
  validates :name, :description, :category, :image, presence: true
  validates :name, uniqueness: true
  #validates :image, :allow_destroy => true
  validates :image, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'Image must be GIF, JPG or PNG format'
  }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}


end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :supplier

  validates :supplier_id, :products_list, presence: true


end

app/models/service_appointment.rb
class ServiceAppointment < ApplicationRecord
  belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :purchase_orders

  validates :name, :country, :city, :address, :postal_code, :company_details, presence: true
  validates :email, :phone, :company, :bank_details, presence: true, uniqueness: true


end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  before_action :authenticate_admin_user!

  private

    def client_params
      params.require(:client).permit(:name, :country, :city, :address,
                                     :postal_code, :email, :phone, :details,
                                     :vehicle_registration_plate, :vehicle_brand,
                                     :vehicle_model, :vehicle_model_details,
                                     :vehicle_life_cycle)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin_user!
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        puts @product.errors.full_messages #verify this assumption
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
        @products = Product.all
        ActionCable.server.broadcast 'products', html: render_to_string('store/index', layout: false)
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image, :description, :category, :price, :quantity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, record)
    if condition
    render record
    end
  end

  def author_off(record)
    admin_user_signed_in? && current_admin_user.id == record.admin_user_id
  end

  def superadmin?
    admin_user_signed_in? && current_admin_user.superadmin?
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchase_orders_helper.rb
module PurchaseOrdersHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :client_name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :client_country %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :client_city %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :client_address %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code, id: :client_postal_code %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :client_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :client_phone %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details, id: :client_details %>
  </div>

  <div class="field">
    <%= form.label :vehicle_registration_plate %>
    <%= form.text_field :vehicle_registration_plate, id: :client_vehicle_registration_plate %>
  </div>

  <div class="field">
    <%= form.label :vehicle_brand %>
    <%= form.text_field :vehicle_brand, id: :client_vehicle_brand %>
  </div>

  <div class="field">
    <%= form.label :vehicle_model %>
    <%= form.text_field :vehicle_model, id: :client_vehicle_model %>
  </div>

  <div class="field">
    <%= form.label :vehicle_model_details %>
    <%= form.text_area :vehicle_model_details, id: :client_vehicle_model_details %>
  </div>

  <div class="field">
    <%= form.label :vehicle_life_cycle %>
    <%= form.text_area :vehicle_life_cycle, id: :client_vehicle_life_cycle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>City</th>
      <th>Address</th>
      <th>Postal code</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Details</th>
      <th>Vehicle registration plate</th>
      <th>Vehicle brand</th>
      <th>Vehicle model</th>
      <th>Vehicle model details</th>
      <th>Vehicle life cycle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.name %></td>
        <td><%= client.country %></td>
        <td><%= client.city %></td>
        <td><%= client.address %></td>
        <td><%= client.postal_code %></td>
        <td><%= client.email %></td>
        <td><%= client.phone %></td>
        <td><%= client.details %></td>
        <td><%= client.vehicle_registration_plate %></td>
        <td><%= client.vehicle_brand %></td>
        <td><%= client.vehicle_model %></td>
        <td><%= client.vehicle_model_details %></td>
        <td><%= client.vehicle_life_cycle %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client.country %>
</p>

<p>
  <strong>City:</strong>
  <%= @client.city %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @client.postal_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<p>
  <strong>Details:</strong>
  <%= @client.details %>
</p>

<p>
  <strong>Vehicle registration plate:</strong>
  <%= @client.vehicle_registration_plate %>
</p>

<p>
  <strong>Vehicle brand:</strong>
  <%= @client.vehicle_brand %>
</p>

<p>
  <strong>Vehicle model:</strong>
  <%= @client.vehicle_model %>
</p>

<p>
  <strong>Vehicle model details:</strong>
  <%= @client.vehicle_model_details %>
</p>

<p>
  <strong>Vehicle life cycle:</strong>
  <%= @client.vehicle_life_cycle %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <% if form.object.image? %>
      <%= image_tag form.object.image.large %>
      <%= form.label :remove_image %>
      <%= form.check_box :remove_image %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, rows: 8, cols: 50 %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category, id: :product_category %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, id: :product_quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th>Category</th>
      <th>Price</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= image_tag product.image.thumb %></td>
        <td><%= product.description %></td>
        <td><%= product.category %></td>
        <td><%= product.price %></td>
        <td><%= product.quantity %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @product.image.medium.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>



<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @product.quantity %>
</p>

<div><%= link_to 'Edit', edit_product_path(@product) %> | <%= link_to 'Back', products_path %></div>