config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #get 'pages/home'
  #root 'store#index', as: 'store_index'

  root to: 'admin/dashboard#index'
  get 'store/index'

  resources :service_appointments
  resources :clients
  resources :products
  resources :purchase_orders
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin_user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if admin_user.superadmin?
    #     can :manage, :admin_user
    #   else
    #     can :read, :admin_user
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :service_appointments
end

app/models/product.rb
class Product < ApplicationRecord

  before_destroy :ensure_not_referenced_by_any_line_item
  #accepts_nested_attributes_for :image, :allow_destroy => true
  mount_uploader :image, ImageUploader
  validates :name, :description, :category, :image, presence: true
  validates :name, uniqueness: true
  #validates :image, :allow_destroy => true
  validates :image, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'Image must be GIF, JPG or PNG format'
  }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}


end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :supplier

  validates :supplier_id, :products_list, presence: true


end

app/models/service_appointment.rb
class ServiceAppointment < ApplicationRecord
  belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :purchase_orders

  validates :name, :country, :city, :address, :postal_code, :company_details, presence: true
  validates :email, :phone, :company, :bank_details, presence: true, uniqueness: true


end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  before_action :authenticate_admin_user!

  private

    def client_params
      params.require(:client).permit(:name, :country, :city, :address,
                                     :postal_code, :email, :phone, :details,
                                     :vehicle_registration_plate, :vehicle_brand,
                                     :vehicle_model, :vehicle_model_details,
                                     :vehicle_life_cycle)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin_user!
  def home
  end
end

app/controllers/service_appointments_controller.rb
class ServiceAppointmentsController < InheritedResources::Base
  before_action :authenticate_admin_user!

  private

    def service_appointment_params
      params.require(:service_appointment).permit(:title, :start_time, :end_time, :appointment_details, :client_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, record)
    if condition
    render record
    end
  end

  def author_off(record)
    admin_user_signed_in? && current_admin_user.id == record.admin_user_id
  end

  def superadmin?
    admin_user_signed_in? && current_admin_user.superadmin?
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/service_appointments_helper.rb
module ServiceAppointmentsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/service_appointments/_form.html.erb
<%= form_with(model: service_appointment, local: true) do |form| %>
  <% if service_appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(service_appointment.errors.count, "error") %> prohibited this service_appointment from being saved:</h2>

      <ul>
      <% service_appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :service_appointment_title %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time, id: :service_appointment_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time, id: :service_appointment_end_time %>
  </div>

  <div class="field">
    <%= form.label :appointment_details %>
    <%= form.text_area :appointment_details, id: :service_appointment_appointment_details %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, id: :service_appointment_client_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/service_appointments/edit.html.erb
<h1>Editing Service Appointment</h1>

<%= render 'form', service_appointment: @service_appointment %>

<%= link_to 'Show', @service_appointment %> |
<%= link_to 'Back', service_appointments_path %>

app/views/service_appointments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Service Appointments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Appointment details</th>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_appointments.each do |service_appointment| %>
      <tr>
        <td><%= service_appointment.title %></td>
        <td><%= service_appointment.start_time %></td>
        <td><%= service_appointment.end_time %></td>
        <td><%= service_appointment.appointment_details %></td>
        <td><%= service_appointment.client %></td>
        <td><%= link_to 'Show', service_appointment %></td>
        <td><%= link_to 'Edit', edit_service_appointment_path(service_appointment) %></td>
        <td><%= link_to 'Destroy', service_appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service Appointment', new_service_appointment_path %>

app/views/service_appointments/new.html.erb
<h1>New Service Appointment</h1>

<%= render 'form', service_appointment: @service_appointment %>

<%= link_to 'Back', service_appointments_path %>

app/views/service_appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @service_appointment.title %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @service_appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @service_appointment.end_time %>
</p>

<p>
  <strong>Appointment details:</strong>
  <%= @service_appointment.appointment_details %>
</p>

<p>
  <strong>Client:</strong>
  <%= @service_appointment.client %>
</p>

<%= link_to 'Edit', edit_service_appointment_path(@service_appointment) %> |
<%= link_to 'Back', service_appointments_path %>