config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  #get 'pages/home'
  #root 'store#index', as: 'store_index'

  root to: 'admin/dashboard#index'
  get 'store/index'

  resources :service_appointments
  resources :clients
  resources :products
  resources :purchase_orders
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(admin_user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if admin_user.superadmin?
    #     can :manage, :admin_user
    #   else
    #     can :read, :admin_user
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :service_appointments
end

app/models/product.rb
class Product < ApplicationRecord

  before_destroy :ensure_not_referenced_by_any_line_item
  #accepts_nested_attributes_for :image, :allow_destroy => true
  mount_uploader :image, ImageUploader
  validates :name, :description, :category, :image, presence: true
  validates :name, uniqueness: true
  #validates :image, :allow_destroy => true
  validates :image, allow_blank: true, format: {
      with: %r{\.(gif|jpg|png)\Z}i,
      message: 'Image must be GIF, JPG or PNG format'
  }
  validates :price, numericality: {greater_than_or_equal_to: 0.01}


end

app/models/purchase_order.rb
class PurchaseOrder < ApplicationRecord
  belongs_to :supplier

  validates :supplier_id, :products_list, presence: true


end

app/models/service_appointment.rb
class ServiceAppointment < ApplicationRecord
  belongs_to :client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :purchase_orders

  validates :name, :country, :city, :address, :postal_code, :company_details, presence: true
  validates :email, :phone, :company, :bank_details, presence: true, uniqueness: true


end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
  before_action :authenticate_admin_user!

  private

    def client_params
      params.require(:client).permit(:name, :country, :city, :address,
                                     :postal_code, :email, :phone, :details,
                                     :vehicle_registration_plate, :vehicle_brand,
                                     :vehicle_model, :vehicle_model_details,
                                     :vehicle_life_cycle)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin_user!
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, record)
    if condition
    render record
    end
  end

  def author_off(record)
    admin_user_signed_in? && current_admin_user.id == record.admin_user_id
  end

  def superadmin?
    admin_user_signed_in? && current_admin_user.superadmin?
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart.html.erb
<article>
  <% if notice %>
    <aside id="notice"><%= notice %></aside>
  <% end %>

  <h2>Your Cart</h2>
  <table>

    <%= render(cart.line_items) %>
    <tfoot>
    <tr>
      <th colspan="2">Total:</th>
      <td class="price"><%= number_to_currency(cart.total_price) %></td>
    </tr>
    </tfoot>
  </table>

  <div class="actions">
    <%= button_to 'Empty cart', cart,
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>


    <%= button_to 'Checkout', new_order_path,
                  method: :get,
                  class: "checkout"%>
  </div>
</article>

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :line_item_product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, id: :line_item_cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr class="line-item-highlight">
  <% else %>
  <tr>
  <% end %>
  <td class="quantity"><%= line_item.quantity %></td>
  <td><%= line_item.product.name %></td>
  <td class="price"><%= number_to_currency(line_item.total_price, :unit => "€") %></td>
</tr>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Order</th>
      <th>Quantity</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.order %></td>
        <td><%= line_item.quantity %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :order_name, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :order_address, rows: 3, cols: 40 %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :order_email, size: 40 %>
  </div>

  <div class="field">
    <%= form.label :pay_type %>
    <%= form.select :pay_type, Order.pay_types.keys, id: :order_pay_type,
                    prompt: 'Select a payment method' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<section class="depot_form">
  <h1>Please Enter Your Details</h1>
  <%= render 'form', order: @order %>
</section>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/store/index.html.erb
<% if notice %>
  <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Products List</h1>

      <table style="width:100%">
        <tr>
          <th>Image: </th>
          <th>Name: </th>
          <th>Category: </th>
          <th>Description: </th>
          <th>Quantity: </th>
          <th>Price: </th>
        </tr>


          <% cache @products do %>
            <% @products.each do |product| %>
              <% cache product do %>
              <tr>
          <td><%= image_tag(product.image.thumb) %></td>
          <td><%= product.name %></h2></td>
          <td><%= product.category %></h3></td>
          <td><p><%= sanitize(product.description) %></p></td>
          <td><%= product.quantity %></td>
          <td><%= number_to_currency(product.price, :unit => "€") %></td>
          <td><%= button_to 'Add to Cart', line_items_path(product_id: product), remote: true %></td>
                </tr>

              <% end %>
            <% end %>
          <% end %>


      </table>

</ul>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>